### ISSUE TITLE
萌新求助返回statsCount是什么意思？

### ISSUE THREAD

**Issue by Johnnydaszhu** [nondanee/Jike-Bus#1]
就是扫码之后的这一步，似乎即刻更新了什么？
my_profile = c.get_my_profile()
my_profile

   113         if res.status_code == 200:
    114             result = res.json()
--> 115             result['user'].update(result['statsCount'])
    116             return User(**result['user'])
    117         res.raise_for_status()

KeyError: 'statsCount'

**Comment by nondanee** [comment]
这个 issue 应该提到 [Jike-Metro](https://github.com/Sorosliu1029/Jike-Metro) 那边吧？
statsCount 应该就是各种计数
```
statsCount:
   { topicSubscribed: 213,
     topicCreated: 0,
     followedCount: 231,
     followingCount: 155,
     highlightedPersonalUpdates: 2,
     liked: 869 }
```
看了下现在确实没有 `result['statsCount']`

**Comment by Johnnydaszhu** [comment]
哦，是的，我把这两个sdk搞混了，唉，之前的不能用怪可惜的
